### ISSUE TITLE
the new stairs 1.14 don't work

### ISSUE THREAD

**Issue by aurel85** [RifleDLuffy/RFChairs#7]
Hi,

I use PaperSpigot 1.14.2 and the last version of this plugin.

I put the new stairs in the config but I can't sit on it. I can on the stairs before 1.14. No error in the console...

Thank you in advance.

**Comment by TheCompieter** [comment]
have the same issue i am using paper also and i got a stack trace.

[22:37:36 WARN]: [RFChairs] Plugin RFChairs v5.3 generated an exception while executing task 462
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
        at com.rifledluffy.chairs.updating.Updater.getLastUpdate(Updater.java:24) ~[?:?]
        at com.rifledluffy.chairs.ChairManager$1.run(ChairManager.java:472) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-94]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-94]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-94]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by totemo** [comment]
While we're talking about stairs (and slabs and carpets), rather than [filtering on material name](https://github.com/RifleDLuffy/RFChairs/blob/master/src/com/rifledluffy/chairs/chairs/StairBlock.java#L17) you might be able to just use [Tag](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html), i.e. `Tag.STAIRS.getValues()`, although you would need to check whether the `LEGACY_` variants are included.
